### ISSUE TITLE
4.1.3 smb xfer mode shows errors (other) while backup is successful

### ISSUE THREAD

**Issue by nauevg** [backuppc/backuppc#159]
Hello.
I installed current version on centos7 from this package - ftp://rpmfind.net/linux/fedora/linux/development/rawhide/Everything/source/tree/Packages/b/BackupPC-4.1.3-4.fc27.src.rpm.
I simply rebuilded package for centos without editing SPEC file.
So, when i do smb backup from w2k8r2 machine - I got backup files, but also i see other errors in stats.
Here is log files:
[win-serv.log](https://github.com/backuppc/backuppc/files/1361485/win-serv.log)
[win-serv.xfer.log](https://github.com/backuppc/backuppc/files/1361484/win-serv.xfer.log)

Full backup ended with 1 other error, increment - with 2 other errors.
In logs increment backup did not copied any files - I run it by hand for tests on same backup data files.
smbclient version - 4.6.2

I searched issues here and internet, but did not found any new info about new smbclient output, instead of that is already included in BPC_4.1.3.

So, any ideas how to fix "other" errors when backup is correct&?

I'm not experienced in programming in perl, but I can do some tests, if someone tell me what to edit.

**Comment by craigbarratt** [comment]
Yes, it's probably the extraneous output from smbclient that isn't recognized by BackupPC.  Let me try to replicate this.

**Comment by nauevg** [comment]
I got this every backup.
But one host generates 2 errors, and other - one error. I attach these log some time later, if needed.

**Comment by craigbarratt** [comment]
I made a commit f1eeb35 that ignores one of the extraneous messages from smbclient.  I tested with smbclient 4.7.  It also flags lines with an "XferErr" if it doesn't recognize the text, so you can tell which line it thinks is an error.

Your xfer.log file is quite short, and it doesn't seem to include the extraneous line that is being counted as an error.

You could apply that commit and see which remaining lines are not recognized.

**Comment by craigbarratt** [comment]
I pushed another commit 1c7cc88 that bases the success / failure of an smb restore on the exit status of smbclient, rather than detecting certain strings in its output.

**Comment by nauevg** [comment]
I applied commit 1c7cc88 and waited for backup to run.
It still shows errors. Now it shows only one error for each smb host. Here logs:
[dc1.xfer.log](https://github.com/backuppc/backuppc/files/1408139/dc1.xfer.log)
[db02.xfer.log](https://github.com/backuppc/backuppc/files/1408140/db02.xfer.log)

**Comment by craigbarratt** [comment]
This output from smbclient was counted as an error;
```
OS=[Windows Server 2008 R2 Enterprise 7601 Service Pack 1] Server=[Windows Server 2008 R2 Enterprise 6.1]
```
I just pushed a commit 3c8f740 to ignore this output.

**Comment by nauevg** [comment]
Hello.
I applied changes in 3c8f740. And there is still one more "XferErr", but it is empty, like this:
...
incr backup started back to 2017-11-15 23:15:01  (backup #36) for share E$
Xfer PIDs are now 30719,30718
tar:1246 Getting files newer than Wed Nov 15 23:15:01 2017
XferErr 
OS=[Windows Server 2008 R2 Standard 7601 Service Pack 1] Server=[Windows Server 2008 R2 Standard 6.1]
tarExtract: /usr/share/BackupPC/bin/BackupPC_tarExtract: got Full = 
...

Previous log was like:
...
tar:1246 Getting files newer than Sun Oct 22 22:00:26 2017
XferErr OS=[Windows Server 2008 R2 Standard 7601 Service Pack 1] Server=[Windows Server 2008 R2 Standard 6.1]
tar:316  tarmode is now full, system, hidden, noreset, quiet
...
OS info on same line as "XferErr" word.

**Comment by craigbarratt** [comment]
Hmmm, not sure why this is happening.

In lib/BackupPC/Xfer/Smb.pm, after the "OS=" patch, try adding this regexp to ignore an empty line.  The first two lines are existing, and the third line is new:
```
                || /^\s*rlimit_max: increasing rlimit_max/i
                || /^\s*OS=\[/i
                || /^\s*$/                   # <- add this line
```

**Comment by nauevg** [comment]
@craigbarratt 
I added regexp for empty line. It is now works fine for 6 days without error messages.
I think we can close issue. Thanks.

**Comment by nauevg** [comment]
@craigbarratt can you add empty line ignoring into code?
I just upgraded my 4.1.3 to 4.1.5 and there no regexp from https://github.com/backuppc/backuppc/issues/159#issuecomment-345567792

**Comment by craigbarratt** [comment]
Ok, I pushed the change 5e70e00.
