### ISSUE TITLE
Cannot use Xfer rsyncd without user and password

### ISSUE THREAD

**Issue by jooola** [backuppc/backuppc#224]
Even with a user/passwordless rsyncd endpoint, I need to fill $Conf{RsyncdPasswd} with a dummy string to get the transfer working. If the password isn't set i face the following error:
```
2018-09-23 02:44:17 User backuppc requested backup of 192.168.100.1 (192.168.100.1)
2018-09-23 02:44:18 Backup failed on 192.168.100.1 (xfer start failed: $Conf{RsyncdPasswd} is empty; host's rsyncd auth will fail)
```

I was on backuppc 3 and I remember a option to disable any auth settings. The setting is still in the config.pl but It doesn't seem to work anyway. 
```perl
$Conf{RsyncdAuthRequired} = '0';                                                                                                                                                                                   
```

I could keep using those dummy infos but this doesn't seem right  I think.

**Comment by craigbarratt** [comment]
Good point.  The $Conf{RsyncdAuthRequired} flag isn't supported in 4.x.  The easiest solution would be to remove $Conf{RsyncdAuthRequired} and allow empty passwords.  Does that sound ok?

**Comment by jooola** [comment]
For me yes, don't know if you are asking maintainers ?

We just need to remove this test : 
https://github.com/backuppc/backuppc/blob/master/lib/BackupPC/Xfer/Rsync.pm#L132

**Comment by craigbarratt** [comment]
Ok, thanks. I just pushed a fix d933bdb.

**Comment by jooola** [comment]
@craigbarratt I just made a fresh install of 4.3.1, and it seems this is not fixed. A empty password will still fail.

**Comment by hamster65** [comment]
same for me. I got around this by entering a random char into the password field.

**Comment by GWHAYWOOD** [comment]
See also #500
