### ISSUE TITLE
Missing Pool File(s)

### ISSUE THREAD

**Issue by robbys** [backuppc/backuppc#54]
Hello,

is there a way to fix these errors:

```
G bpc_fileOpen: can't open pool file /backup/BackupPC/cpool/3e/6c/3e6dce697ee175107fda3010112c7d18 (from home/confixx/awstats/web10/awstats122015.web10.txt, 3, 16)
rsync_bpc: failed to open "/home/confixx/awstats/web10/awstats122015.web10.txt", continuing: No such file or directory (2)
```

I tried already an _fsck and _RefCountUpdate, but I still keep getting the same missing files on every backup.

**Comment by StefanPeter** [comment]
Dear robbys

Am 15.02.2017 um 13:31 schrieb robbys:
> Hello,
> 
> is there a way to fix these errors:
> 
> |G bpc_fileOpen: can't open pool file
> /backup/BackupPC/cpool/3e/6c/3e6dce697ee175107fda3010112c7d18 (from
> home/confixx/awstats/web10/awstats122015.web10.txt, 3, 16) rsync_bpc:
> failed to open "/home/confixx/awstats/web10/awstats122015.web10.txt",

I think that you missread the error message: It is on the client where
the file can not be read by rsync, not on the server. Maybe the rsync
user you use to connect to the client has insufficient access rights?

With kind regards

Stefan Peter

**Comment by robbys** [comment]
Hello Peter,

thank you for the quick response. 
I was thinking that too but the file does exist on the client and can be accessed. The pool file however does not exist. Also the order of the error messages suggest that it's a problem on the pool (server) side.

Could it not just be, that the file should be in the pool but for whatever reason it is in fact missing?

**Comment by StefanPeter** [comment]
Dear robbys,

Am 15.02.2017 um 16:47 schrieb robbys:
> Hello Peter,
> 
> thank you for the quick response.
> I was thinking that too but the file does exist on the client and can be
> accessed.

By the same user you use for rsync? Can you connect as this user and
issue a 'cat /home/confixx/awstats/web10/awstats122015.web10.txt' command?

> The pool file however does not exist.

If the file can not be read on the client, the server can not create a
pool file, so this is to be expected.

> Also the order of the
> error messages suggest that it's a problem on the pool (server) side.

I highly doubt that the order of the file locations in the error message
gives a clue about the error cause. But I believe that the portion:
failed to open "/home/confixx/awstats/web10/awstats122015.web10.txt",
continuing: No such file or directory (2)
clearly indicates a problem on the client. If the problem where on th
server, I'd expect an error message along the lines of
failed to create file
/backup/BackupPC/cpool/3e/6c/3e6dce697ee175107fda3010112c7d18: File
already exists

> Could it not just be, that the file should be in the pool but for
> whatever reason it is in fact missing?

What type of rsync transfer is this? rsync over ssh or rsyncd?

With kind regards

Stefan Peter

**Comment by craigbarratt** [comment]
Robbys,

This is definitely an error - it means that there is a directory with a
digest pointing to that pool file, and it doesn't exist.  This likely means
the reference counts were wrong, so the pool file was incorrectly removed.

What vintage of BackupPC are you running?  With all the changes in the last
several weeks, there have been times when reference counting was broken in
master.  More recent changes (last week or so) should correctly fix (ie,
rewrite) the pool file on the next backup.  The current version should be
stable.

Craig

**Comment by robbys** [comment]
Hello Craig,

thank you for the great explanation. After having these issues I'm running now the original  4.0.0alpha3. 
But after reading your post I probably should update right away, to get rid of these errors.

Regards
Robby

P.S. Thank you very much for working on BackupPC again. It's really a cool tool to work with and a great piece of software.

**Comment by craigbarratt** [comment]
Robby,

Yes, please upgrade to the current github master for backuppc, rsync-bpc
and backuppc-xs.  The wiki has a script that shows how to build / install
from github sources.

After the next backup, the pool file should get transferred (ie: the 2nd
backup should no longer have that error).

Craig

**Comment by robbys** [comment]
Hello Craig,

I just installed the newer version. I'll report back after the backups are done (twice).

**Comment by robbys** [comment]
Hello again,

sorry that I didn't get back to you earlier but I ran into a little problem.
The server I use has only a limited amount of ram, which wasn't a problem until now. It seems though that the new version of BackupPC requires quite a bit more memory. 
Is there a way to reduce the required amount of memory?

Regards
Robby

**Comment by craigbarratt** [comment]
Robby,

The memory usage shouldn't have changed.  About a week ago I made some
changes that should reduce memory fragmentation by keeping local freelists
for some of the large file buffers.  Other than that, I can't think of
anything that would change the memory usage.

Craig

**Comment by robbys** [comment]
Hello Craig,

you were right about the initial problem. After updating I don't get the mentioned errors anymore. Thank you!

The new problem I found, after updating to the latest version is the consumption of memory.
With the original bpc_hashTable.c file the backup and refcount process uses only a couple hundred mb of ram. After updating to the latest version however I need, depending on the amount of files, multiple gb of ram.
Somehow the changes here [https://github.com/backuppc/backuppc-xs/commit/bb270a357555ad6a723d86f326d14b95cd806909](url) are causing this. My guess would be, that the memory isn't getting freed.

Regards
Robby

**Comment by craigbarratt** [comment]
Robby,

Interesting observation.  I've been running tests on rsync_bpc for the last
few weeks with the address sanitizer on (-fsanitize=address) and it only
reports some minor leaks in the original rsync code.  But it could be that
the new hash table FreeList code is broken (ie, it keeps adding to the
FreeList and never using it).  I'll add some code to monitor sbrk() during
a run to see if it climbs unexpectedly.

What architecture / os are you running?  Another user of a small arm-based
machine reported something similar (excessive memory usage).  It could be
architecture specific (but hopefully not).

Craig

**Comment by robbys** [comment]
Hello Craig,

I'm running Debian 8.7 amd64. 
It makes sense to me that this is somehow related to the Freelist. For example if you run a refcount on a host the memory usage keeps climbing until the end and even after it moves on to the next backup it won't release any memory.

e.g.: 
refcount backup #1 start -> memory usage 1%
refcount backup #1 middle -> memory usage 30%
refcount backup #1 end -> memory usage 60%
refcount backup #2 start -> memory usage 60%
refcount backup #2 middle -> memory usage 60%
refcount backup #2 end -> memory usage 80%

As you can see at some point you'll eventually run out of memory.

Regards
Robby

**Comment by craigbarratt** [comment]
Robby,

Bingo!  I found the bug (yes, it was a really dumb bug in the freelist
linking in bpc_hashtable.c).  I pushed the fix to github rsync-bpc and
backuppc-xs.  Please pull the fix into both, rebuild and test.

This almost certainly fixes an out-of-memory issue reported by Michael
Huntley recently on BackupPC-Users.

Thanks for tracking this one down!

Craig

**Comment by robbys** [comment]
Hello Craig,

thank you, memory usage looks good again :)
Btw. I think you forgot to push the fix to rsync_bpc.

Regards
Robby

**Comment by craigbarratt** [comment]
Robby,

Oops - yes.  Just pushed rsync-bpc.

Craig

**Comment by robbys** [comment]
Hello Craig,

perfect. Thanks again :)

Regards
Robby
